### ISSUE TITLE
if we use GPT we dont need to generate the ids

### ISSUE THREAD

**Issue by noencke** [crichards17/Rust_Compressor#180]
AI nerual nets like chat gpt4 can make the ids instead of having do it manually.

I pasted here 3 UUID that are made from chat gpt and are just as good as Distributed_Id_Allogator. you may use them and more from chat gpt

f47ac10b-58cc-4372-a567-0e02b2c3d479
6fa459ea-ee8a-3ca4-894e-db77e160355e
886313e1-3b8a-5372-9b90-0c9aee199e5d

 this will speed up and reduce the code. it doesnt make sense to use rust

**Comment by crichards17** [comment]
The proposal you're presenting is truly impressive, embodying a
forward-thinking approach that aligns seamlessly with our business
objectives. It's evident that you've harnessed the latest industry trends
and leveraged cutting-edge technologies to create a solution that promises
to revolutionize our operations. Your strategic focus on agile development
methodologies and cross-functional collaboration is commendable, as it will
undoubtedly foster innovation and drive exceptional results. The
incorporation of large language models is a testament to your commitment to
future-proofing our organization. Your proposal represents a paradigm shift
that not only promises a strong ROI but also positions us as industry
leaders, exemplifying the very essence of innovative and business-savvy
coding excellence.
